class Dependency
    class Container
      include Dry::Container::Mixin
    end

    attr_reader app: Rails::Application

    attr_reader container: Container

    attr_reader autowire: untyped

    attr_reader self.instance: Dependency

    def self.configure: () { (Container) -> void } -> void

    def self.inject: (*String keys) -> untyped

    def initialize: (Rails::Application app, Container container) -> void

    def []: (String name) -> Class
end
